version: "3.4"
services:

  # Banco de dados
  postgres:
    image: postgres
    container_name: "postgres"
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: secret
    networks:
      - codenation

networks: 
  codenation:
    driver: bridge
    external:
      name: codenation
      