# Generated by Django 2.2.3 on 2019-08-05 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '__first__'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('pet_type', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=1024)),
                ('city', models.CharField(max_length=1024)),
                ('neighborhood', models.CharField(blank=True, max_length=1024, null=True)),
                ('contact_name', models.CharField(max_length=100)),
                ('phone_1', models.CharField(blank=True, max_length=12, null=True)),
                ('phone_2', models.CharField(blank=True, max_length=12, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.Album')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.Category')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.Gender')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.Size')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
    ]
