# Generated by Django 2.2.3 on 2019-07-26 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('phone_1', models.CharField(max_length=9)),
                ('phone_2', models.CharField(max_length=9)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pet_type', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=1024)),
                ('state', models.CharField(max_length=1024)),
                ('neighborhood', models.CharField(max_length=1024)),
                ('zipcode', models.CharField(max_length=12)),
                ('description', models.CharField(max_length=1024)),
                ('contact', models.CharField(max_length=1024)),
            ],
        ),
    ]
