# Generated by Django 2.2.3 on 2019-07-27 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='pet',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.Contact'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.Size'),
        ),
    ]
