# Generated by Django 2.2.3 on 2019-07-27 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_auto_20190726_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='contact',
        ),
        migrations.AddField(
            model_name='pet',
            name='contact_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='phone_1',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='pet',
            name='phone_2',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
