# Generated by Django 2.2.3 on 2019-07-29 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '__first__'),
        ('pets', '0004_auto_20190726_2152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='pet',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.Album'),
        ),
        migrations.AddField(
            model_name='pet',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
