# Generated by Django 2.2.4 on 2019-08-17 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_auto_20190814_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='category',
            field=models.CharField(blank=True, choices=[('ENCONTRADOS', 'ENCONTRADOS'), ('PROCURA_SE', 'PROCURA_SE'), ('ADOCAO', 'ADOCAO')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='category_status',
            field=models.CharField(blank=True, choices=[('ACHEI_MEU_DONO', 'ACHEI_MEU_DONO'), ('PROCURANDO_MEU_DONO', 'PROCURANDO_MEU_DONO'), ('FUI_ADOTADO', 'FUI_ADOTADO')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='CategoryStatus',
        ),
    ]
