# Generated by Django 2.2.4 on 2019-08-23 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0013_auto_20190818_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='category_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_status', to='pets.CategoryStatus'),
        ),
        migrations.CreateModel(
            name='PetStatusHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pets.CategoryStatus')),
                ('pet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pets.Pet')),
            ],
        ),
    ]
