CATEGORIES = (
    ('ENCONTRADOS', 'ENCONTRADOS'),
    ('PROCURA_SE', 'PROCURA_SE'),
    ('ADOCAO', 'ADOCAO')
)

CATEGORIES_STATUS = (
    ('ACHEI_MEU_DONO', 'ACHEI_MEU_DONO'),
    ('PROCURANDO_MEU_DONO', 'PROCURANDO_MEU_DONO'),
    ('FUI_ADOTADO', 'FUI_ADOTADO')
)
